fix PHP 8.5 deprecation warnings
RuntimeException: Non-canonical cast (double) is deprecated, use the (float) cast instead on line 7281 in file /path/to/econea/nusoap/src/nusoap.php
RuntimeException: Non-canonical cast (boolean) is deprecated, use the (bool) cast instead on line 7287 in file /path/to/econea/nusoap/src/nusoap.php
RuntimeException: Function xml_parser_free() is deprecated since 8.5, as it has no effect since PHP 8.0 on line 6916 in file /path/to/econea/nusoap/src/nusoap.php